main_function: main_11 main_12 main_13 main_14 main_21 main_22 main_23 main_24 main_31 main_32 main_33 main_34 main_41 main_42 main_43 main_44 main_51 main_52 main_53 main_54 
	 @echo "================================================================="
	 @echo "RLE Encode and Decode - Unoptimized - 2 characters - size 100x100: "
	 @./main_11
	 @echo "================================================================="
	 
	 @echo "RLE Encode and Decode - Optimized OpenMP - 2 characters - size 100x100: "
	 @./main_12
	 @echo "================================================================="
	 
	 @echo "RLE Encode and Decode - Unoptimized - 5 characters - size 100x100: "
	 @./main_13
	 @echo "================================================================="
	 
	 @echo "RLE Encode and Decode - Optimized OpenMP - 5 characters - size 100x100: "
	 @./main_14
	 @echo "================================================================="
	 
	 
	 
	 
	 @echo "================================================================="
	 @echo "RLE Encode and Decode - Unoptimized - 2 characters - size 200x200: "
	 @./main_21
	 @echo "================================================================="
	 
	 @echo "RLE Encode and Decode - Optimized OpenMP - 2 characters - size 200x200: "
	 @./main_22
	 @echo "================================================================="
	 
	 @echo "RLE Encode and Decode - Unoptimized - 5 characters - size 200x200: "
	 @./main_23
	 @echo "================================================================="
	 
	 @echo "RLE Encode and Decode - Optimized OpenMP - 5 characters - size 200x200: "
	 @./main_24
	 @echo "================================================================="
	 
	 
	 

	 @echo "================================================================="
	 @echo "RLE Encode and Decode - Unoptimized - 2 characters - size 300x300: "
	 @./main_31
	 @echo "================================================================="
	 
	 @echo "RLE Encode and Decode - Optimized OpenMP - 2 characters - size 300x300: "
	 @./main_32
	 @echo "================================================================="
	 
	 @echo "RLE Encode and Decode - Unoptimized - 5 characters - size 300x300: "
	 @./main_33
	 @echo "================================================================="
	 
	 @echo "RLE Encode and Decode - Optimized OpenMP - 5 characters - size 300x300: "
	 @./main_34
	 @echo "================================================================="



	 @echo "================================================================="
	 @echo "RLE Encode and Decode - Unoptimized - 2 characters - size 500x500: "
	 @./main_41
	 @echo "================================================================="
	 
	 @echo "RLE Encode and Decode - Optimized OpenMP - 2 characters - size 500x500: "
	 @./main_42
	 @echo "================================================================="
	 
	 @echo "RLE Encode and Decode - Unoptimized - 5 characters - size 500x500: "
	 @./main_43
	 @echo "================================================================="
	 
	 @echo "RLE Encode and Decode - Optimized OpenMP - 5 characters - size 500x500: "
	 @./main_44
	 @echo "================================================================="

	 
	 
	 
	 @echo "RLE Encode and Decode - Unoptimized - 2 characters - size 800x800: "
	 @./main_51
	 @echo "================================================================="
	 
	 @echo "RLE Encode and Decode - Optimized OpenMP - 2 characters - size 800x800: "
	 @./main_52
	 @echo "================================================================="
	 
	 @echo "RLE Encode and Decode - Unoptimized - 5 characters - size 800x800: "
	 @./main_53
	 @echo "================================================================="
	 
	 @echo "RLE Encode and Decode - Optimized OpenMP - 5 characters - size 800x800: "
	 @./main_54
	 @echo "================================================================="
	
	
	
main_11: RLEencode11.cpp
	 g++ RLEencode11.cpp -o main_11
	 	 
main_12: RLEencode12.cpp
	 g++ RLEencode12.cpp -O3 -fopenmp -o main_12
	 
main_13: RLEencode13.cpp
	 g++ RLEencode13.cpp -o main_13
	 	 
main_14: RLEencode14.cpp
	 g++ RLEencode14.cpp -O3 -fopenmp -o main_14
	 


main_21: RLEencode21.cpp
	 g++ RLEencode21.cpp -o main_21
	 	 
main_22: RLEencode22.cpp
	 g++ RLEencode22.cpp -O3 -fopenmp -o main_22
	 
main_23: RLEencode23.cpp
	 g++ RLEencode23.cpp -o main_23
	 	 
main_24: RLEencode24.cpp
	 g++ RLEencode24.cpp -O3 -fopenmp -o main_24
	 
	 
main_31: RLEencode31.cpp
	 g++ RLEencode31.cpp -o main_31
	 	 
main_32: RLEencode32.cpp
	 g++ RLEencode32.cpp -O3 -fopenmp -o main_32
	 
main_33: RLEencode33.cpp
	 g++ RLEencode33.cpp -o main_33
	 	 
main_34: RLEencode34.cpp
	 g++ RLEencode34.cpp -O3 -fopenmp -o main_34
	 
	 
	 
main_41: RLEencode41.cpp
	 g++ RLEencode41.cpp -o main_41
	 	 
main_42: RLEencode42.cpp
	 g++ RLEencode42.cpp -O3 -fopenmp -o main_42
	 
main_43: RLEencode43.cpp
	 g++ RLEencode43.cpp -o main_43
	 	 
main_44: RLEencode44.cpp
	 g++ RLEencode44.cpp -O3 -fopenmp -o main_44
	 
	 

main_51: RLEencode51.cpp
	 g++ RLEencode51.cpp -o main_51
	 	 
main_52: RLEencode52.cpp
	 g++ RLEencode52.cpp -O3 -fopenmp -o main_52
	 
main_53: RLEencode53.cpp
	 g++ RLEencode53.cpp -o main_53
	 	 
main_54: RLEencode54.cpp
	 g++ RLEencode54.cpp -O3 -fopenmp -o main_54